### ISSUE TITLE
Remove and ignore .DSstore files

### ISSUE THREAD

**Issue by BarkleyBG** [TarHeelBiostatistics/DoctoralThesisTexTemplate#10]
- [x] Remove the three .DSstore files from the repo
- [x] Ignore all of those file extensions (`*.DSstore`) to prevent this problem in the future

**Comment by phoebejiang** [comment]
I submitted a pull request.

**Comment by BarkleyBG** [comment]
Could you please use the hashtag/pound sign to refer to the pull request?

**Comment by phoebejiang** [comment]
Sorry, my bad. 

I submitted a pull request, see here #11 
I removed the .DSstore from my local machine (only found one in the main folder, didn't see the other two) and added *.DS_store to the .gitignore file

**Comment by phoebejiang** [comment]
Fixes #10.

**Comment by BarkleyBG** [comment]
This should have auto-closed with #11 but it didn't for some reason. I'm checking the boxes and marking this as closed. Good job!
