### ISSUE TITLE
Standalone .tex template or R package?

### ISSUE THREAD

**Issue by bsaul** [TarHeelBiostatistics/DoctoralThesisTexTemplate#2]
Should we develop this template as a standalone .tex template? Or put it in an rpackage so that it can be called from `rmarkdown::draft()`, e.g.:
`rmarkdown::draft("MyJSSArticle.Rmd", template = "jss_article", package = "rticles")`

**Comment by BarkleyBG** [comment]
Setting an end goal of making this an rpackage may be a good idea. 

I also think that, until then, it may be good to get a 'working copy' out with all its warts.

**Comment by BarkleyBG** [comment]
As of 7a60478e18f1085633de354d37c8d27c51e5c413, this template can be:

1. Used on its own in a TeX front-end program
2. Called from RMarkdown via the YAML header commands shown in the README file

However, it is not yet in an rpackage and so cannot be called from ``rmarkdown::draft()``, correct?

**Comment by bsaul** [comment]
That is correct.

**Comment by BarkleyBG** [comment]
Shall we close this for now and concentrate on the Rmd template we have currently?

**Comment by bsaul** [comment]
Sure, yes.
