### ISSUE TITLE
Unpack Template 2 into similar format as Template 1

### ISSUE THREAD

**Issue by BarkleyBG** [TarHeelBiostatistics/DoctoralThesisTexTemplate#7]
@bcjaeger was kind enough to add his template to this repo. It's in a zipped file, [here](https://github.com/TarHeelBiostatistics/DoctoralThesisTexTemplate/blob/master/UNC%20Dissertation%20LaTeX%20Template.zip). I would like it better if this template were unzipped and put in a style more similar to the sub-directory for Template 1. 

My estimate is that the difficulty level is:
- git: low/med
- tex: low

@bcjaeger @phoebejiang @djluckett @cttnguyen which of you would like to do this? I can walk you through it.

**Comment by phoebejiang** [comment]
Me! I'll be on campus tomorrow afternoon.

**Comment by phoebejiang** [comment]
I uploaded Byron's unzipped file under Template 2. I kept the folders "common" and "front matter" the way they were, changed the main TEX into the name "START_HERE_main_template", and got rid of the .log, .pdf, ... files, keeping only the TEX file.

**Comment by BarkleyBG** [comment]
Could you please:

1. Remove all .log, .dvi, etc files from the subfolder "common"?
2. remove the .DSstore from the main directory and the Template 2 subfolder?

**Comment by phoebejiang** [comment]
Okay. You might have showed me already, but how do I remove files? 
I was trying to do it and I think I added another folder that I don't want..

**Comment by BarkleyBG** [comment]
You'll need to remove the files from your local copy of the repository. Then, you can either push (or, better, use a pull request) to have this remote repository look like your local copy.

1. Remove the files from your local repo - that is, the folder on your computer.
2. Commit these file changes on your local repo
3. push these changes to the remote repo

After you're done with that, I'll have you 
4. make changes to the .gitignore so this doesn't happen again 
5. fork the repo and use pull requests (instead of pushing changes)

**Comment by phoebejiang** [comment]
Done with 1-3. Ready for 4 and 5. 
There are three .DS_Store files that we need to remove.

**Comment by phoebejiang** [comment]
@bcjaeger, what is that UNC-dissertation_concordance.tex for? I was able to compile without it.

**Comment by BarkleyBG** [comment]
Phoebe I am moving step 4 here to #8, and let's let someone else take it.

For now, please fork the repo to your github account. I want you to make that the remote repo that you push to by default. So, you'll need to change your local github gui (aka program on the desktop) so that it pushes to your remote forked repo, and not this remote repo for the THB group.  

Here's the steps, after you fork: On your forked repo, hit the 'clone/download' button and then "copy to clipboard" that URL. Find the settings tab in your github desktop gui for remote repository, and then paste the forked repo's URL in that spot. 

If you have problems, fork the repo and file a new issue in your repo (and @ me) and I'll respond later in the week

**Comment by phoebejiang** [comment]
I think I did it. Would you mind checking it when you have time? Thanks!

**Comment by BarkleyBG** [comment]
Yes, you've forked. Good! You may want to change the settings of your fork to allow me to file issues.

Now, could you 
1. locally, create (and check out) a new branch called "DSstore"
2. push that branch to your remote (forked) repo - - not this repo here

**Comment by phoebejiang** [comment]
I created the new branch in my forked repo. I don't know how to allow you to file issues but I invited you as a collaborator, maybe this helps? I started a new issue in my repo.

**Comment by bsaul** [comment]
This was also dealt with in #6
