### ISSUE TITLE
Ignore more files in the .gitignore

### ISSUE THREAD

**Issue by BarkleyBG** [TarHeelBiostatistics/DoctoralThesisTexTemplate#8]
We need to ignore a few types of files that are not useful. The .tex files are useful; the .aux, .log, etc files are not useful because they are generated from the .tex files.

We can ignore not useful files. Ignoring them does two things: (1) they allow the files to persist in our local folders (2) they do not save the files to the git history, which means that they will not clutter up the repo. We ignore the pdf file because we don't want to see it in the history, but we DO want to see it in our local directory.

File extensions to be added to the .gitignore file:

- .log
- .gz
- .dvi
- .aux
- .DSstore

To ignore these, simply add a line to the .gitignore file with `*.dvi` to ignore all files (*) with the extension .dvi. 

@cttnguyen @djluckett  could one of you take this on?

1. pull down most recent changes from the remote
2. make the above changes to the .gitignore file
3. make a pull request and describe these changes in the pull request

**Comment by BarkleyBG** [comment]
Actually, let's hold off on this until we decide #9

**Comment by BarkleyBG** [comment]
ok, ready to go! @cttnguyen and/or @djluckett write a comment below when you're ready to do this.

Daniel as a first step, you'll need to fork this repo to your github account. Crystal has already done this. Both of you will need to verify that your local github desktop gui is set up to push changes to your remote fork (Phoebe just accomplished this, so feel free to ask her or me if you have problems)

Before you make the changes listed above, create and check out a new branch (called, "ignoreissue" or something) and make the changes in this branch, never in the master branch.

**Comment by phoebejiang** [comment]
Reminder: the .DSstore file should be .DS_Store.

**Comment by BarkleyBG** [comment]
and also these file extensions should be preceded by the `*` in the .gitignore file

**Comment by BarkleyBG** [comment]
Bump. Could one of you guys please take care of this and submit a PR this week? #6 will probably require the updated .gitignore file.

**Comment by phoebejiang** [comment]
I have submitted a PR #15. I will take a look at #6 more after this issue is closed.

**Comment by BarkleyBG** [comment]
Thanks! Please make explicit linked references to the PR for ease.

**Comment by phoebejiang** [comment]
Gotcha.
