### ISSUE TITLE
Roll back history?

### ISSUE THREAD

**Issue by BarkleyBG** [TarHeelBiostatistics/DoctoralThesisTexTemplate#9]
Today's commit history is messy. Perhaps we should force-push a cleaned up version? I think we should possibly roll back the master commit to bbf6a9e96bb212b2224679b5f3e6c7a7f648e4b6 and try to unpack template 2 (i.e. issue #7 ) again.

@bsaul, what do you think? Do you think it's better to keep today's commits as a learning experience? Or do you think rolling back and trying it again would make things a lot more clear? Thanks for looking at it!

**Comment by bsaul** [comment]
As long as the code is clean moving forward, I don't think the history matters all that much at this stage in the project.

**Comment by BarkleyBG** [comment]
ok, thanks for the advice. Closing this and proceeding as-is.
